#+OPTIONS: prop:t

#+TITLE:     Rezept
#+EMAIL:     e.fraga@ucl.ac.uk
#+DATE:      2010-03-30 Tue
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:https://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 

#+BEAMER_FRAME_LEVEL: 4


* Lentil Salad with Summer Vegetables
:PROPERTIES:
:source-url: https://www.simplyrecipes.com/recipes/lentil_salad_with_summer_vegetables/
:servings: ngs
:prep-time: 10 minutes
:cook-time: 25 minutes
:ready-in: nil
:END:

** Ingredients

- 1 cup Puy lentils
- 2 cloves garlic
- 1 bay leaf
- Handful of parsley stems, tied together with a string
- 2 1/2 cups water
- 3 stalks celery, diced small
- 1 yellow pepper, diced
- 1 pint grape or cherry tomatoes, halved
- 1/4 cup minced red onion
- 1 cup baby arugula
- 3 tablespoons lemon juice
- 3 tablespoons extra virgin olive oil
- 1 tablespoon fresh minced parsley
- Zest from 1/2 lemon
- 1/2 teaspoon Morton kosher salt
- 1/4 teaspoon dried oregano
- 1/4 teaspoon sugar
- 1 tablespoon minced shallots
- Salt and pepper to taste


** Directions

1. : In a medium pot combine lentils, smashed garlic cloves, bay leaf, a handful of parsley stems. Add enough water to cover the lentils by 1 1/2 to 2 inches (about 2 1/2 cups).
2. Bring to a simmer and cook uncovered for about 25 minutes. The exact time will vary based on how dry the lentils are. When you get about 10 minutes out from the finished cooking time, start sampling the lentils to check for doneness—when cooked, they should be tender, but still intact. Continue sampling every 5 minutes until they’re ready.
3. When the lentils are done, drain them and discard the bay leaf, garlic, and parsley stems.
   

* Selbst gemachte, gerollte Maultaschen
:PROPERTIES:
:source-url: https://www.chefkoch.de/rezepte/3214541478365342/Selbst-gemachte-gerollte-Maultaschen.html
:servings: 10
:prep-time: 45 Min
:cook-time: 15 Min
:ready-in: 
:END:      

** Ingredients

- 1  Zwiebel(n), gewürfelt
- 50 g Lauch, fein geschnitten
- 50 g Speck
- 450 g Rahmspinat
- 1 kg Hackfleisch, gemischt
- 3  Ei(er)
- 8 EL Paniermehl
- 1  1 / 2  TL Salz
- 1 TL Oregano oder Majoran
  Salz und Pfeffer

** Directions

1. Speck, Zwiebeln und Lauch in einer Pfanne abraten. Mit Oregano, etwas Salz und Pfeffer
   würzen. Dann den etwas angetauten Spinat dazugeben. Etwas einkochen, dann abkühlen lassen.

2. Das Hackfleisch mit ca. 1,5 TL gut salzen. Von den Eiern ein Eiweiß fürs spätere Bestreichen zur
   Seite stellen. Den Rest zum Hackfleisch geben. Das Paniermehl dazu, dann die etwas abgekühlte
   Gemüsemischung und alles verkneten. Evtl. noch etwas mehr Paniermehl verwenden, sodass eine
   streichfähige Masse entsteht.

2. Vom Nudelteig so viel abwickeln, dass mindestens 30 cm frei liegen. Davon ca. 20 - 25 cm mit der
   Masse ca. 0,5 cm dick bestreichen.

3. Danach ca. 3 cm mit Eiweiß bestreichen. Dies ist die "Klebekante". Dort abschneiden und von der
   anderen Seite aufrollen. Dann diese Rolle in 4 - 6 Maultaschen schneiden.

4. Dieses Vorgehen solange wiederholen, bis Teig aufgebraucht ist. Falls von der Hackmasse noch
   etwas übrig ist, kann man Klöße formen und diese später auch kochen.

5. Nun die Maultaschen portionsweise in kochendes Wasser legen und ca. 10 - 15 min. ziehen lassen. 


* Maultaschen nach BodenseeOmi
:PROPERTIES:
:source-url: https://www.simplyrecipes.com/recipes/lentil_salad_with_summer_vegetables/
:servings: ngs
:prep-time: 120 minutes
:cook-time: 15 minutes
:ready-in: 3h
:END:      
**** Ingredients

- 350g Hackfleisch
- 250g Brät
- 1.20m Nudelteig von Bäcker Stüble-Wurster
- Spinat oder Zwiebelröhrle
- 2 Brötchen / 2 Eier (pro Brötchen ein Ei)
- Petersilie
- 1 Zwiebel

**** Directions

- Kochdauer:: 15 min in Brühe ziehen lassen
- Metzgerei Huber: 07532 445866




* Grünkohl, wie ihn Mutter kochte
:PROPERTIES:
:source-url: https://www.chefkoch.de/rezepte/237101096472618/Gruenkohl-wie-ihn-Mutter-kochte.html
:servings: 8
:prep-time: 30 Min
:cook-time: nil
:ready-in: 
:END:

** Ingredients

- 2,4 kg Grünkohl, tiefgefroren
- 4  Zwiebel(n)
- 50 g Schmalz (Gänseschmalz)
- 1 Liter Fleischbrühe, doppelt konzenttrierte (Brühwürfel für 2,5 ltr. Wasser in 1 ltr. auflösen)
- 2 EL Senf, mittelscharf
- 10  Würste (Pinkelwürste *)
- 8  Würste (Kohlwürste, geräucherte Mettenden)
- 500 g Speck, geräucherter, gestreifter
- 8  Kasseler - Koteletts
  Haferflocken


* Skirt Steak with Chimichurri Sauce Recipe
:PROPERTIES:
:source-url: https://steamykitchen.com/15405-skirt-steak-with-chimichurri-sauce.html
:servings: 4
:prep-time: 15 minutes
:cook-time: 15 minutes
:ready-in: nil
:END:

** Ingredients

- FOR THE CHIMICHURRI
- 1 cup packed fresh flat-leaf parsley leaves
- 1 cup fresh oregano leaves
- 4 cloves garlic, minced
- 2 teaspoons crushed red pepper flakes
- 1/4 cup red wine vinegar
- 1/2 cup extra virgin olive oil
- sea salt
- FOR THE SKIRT STEAK
- 2 pounds skirt steak, excess fat trimmed
- salt and freshly ground black pepper


** Directions

1. To make the chimichurri, combine all of the ingredients together in a small bowl.
2. Season the skirt steak on both sides with salt and pepper. Grill 2-3 minutes on each side over
   high heat. Lower heat to medium, cover and cook for an additional 2 minutes for medium-rare (If
   your skirt steak is 1/2" thick or less, skip this step.)
3. Let steak rest for 5 minutes before slicing. Slice across the grain. Serve with Chimichurri
   Sauce.


* Hausfreunde 
:PROPERTIES:
:source-url: https://www.chefkoch.de/rezepte/586771157900105/Hausfreunde-mit-Marzipan.html
:servings: 1
:prep-time: nil
:cook-time: nil
:ready-in:
:END:

** Hausfreunde 

** Zutaten

Zutaten für 4 Personen
- 175 g 	Mehl
- 75 g 	Speisestärke
- 65 g 	Zucker
- 1 Pck. 	Vanillinzucker
- 1 	Ei(er)
- 165 g 	Butter
- etwas 	Aprikosenkonfitüre
- 200 g 	Marzipan - Rohmasse
- 100 g 	Puderzucker
- Kuchenglasur, Schoko
- Walnüsse (Hälften)


** Directions

- Aus Mehl, Speisestärke, Zucker, Vanillinzucker, Ei und Butter einen Mürbteig herstellen. Im
  Kühlschrank ca. 1 Stunde ruhen lassen.

- Messerdick ausrollen und mit einem runden Förmchen ausstechen. Auf ein mit Backpapier belegtes
  Backblech geben und bei 180°C ca. 10 Minuten backen.

- Nach dem Erkalten je ein Plätzchen mit Marmelade bestreichen und mit einem 2. zusammensetzen.

- Marzipan und Puderzucker miteinander verkneten und dünn ausrollen. Wieder mit runden Förmchen ausstechen.

- Die Plätzchen nochmals mit Marmelade bestreichen und auf jedes ein ausgestochenes Marzipanteil geben.

- Mit Schokoglasur bestreichen und mit einer Walnusshälfte verzieren. 
