#+title: README


* Doom Flavor

doom has got an environment file:

doom help env

* Building Emacs

** Directory Structure

Following a clean, organized directory structure:

#+begin_src
~/local/                      # Base directory for local software
├── src/                      # Source code for software to be compiled
│   ├── emacs/                # Emacs source code
│   ├── texinfo/              # Texinfo source code
│   └── ...
├── build/                    # Build directories (keeps source dir clean)
│   ├── emacs/                # Emacs build directory
│   ├── texinfo/              # Texinfo build directory
│   └── ...
├── opt/                      # Installed software (similar to /opt)
│   ├── emacs/                # Emacs installation
│   ├── texinfo/              # Texinfo installation
│   └── ...
├── bin/                      # Symlinks to installed binaries
├── lib/                      # Libraries for local software
├── include/                  # Header files for local software
├── share/                    # Shared data files
├── var/                      # Variable data (logs, etc.)
└── etc/                      # Configuration files
#+end_src

** Local Build

#+begin_src bash
# Create necessary directories
mkdir -p ~/local/{src,build,opt,bin,lib,include,share,var,etc}

# Get Emacs source code
cd ~/local/src
git clone https://git.savannah.gnu.org/git/emacs.git
cd emacs

# Create and use build directory
mkdir -p ~/local/build/emacs
cd ~/local/build/emacs

# Generate configuration files
~/local/src/emacs/autogen.sh

# Configure with appropriate paths
~/local/src/emacs/configure \
  --prefix=$HOME/local/opt/emacs \
  --bindir=$HOME/local/bin \
  --with-native-compilation \
  --with-mailutils \
  --with-tiff=ifavailable \
  --with-gnutls=ifavailable

# Build and install
make -j$(nproc)
make install

# Add to PATH if not already there
echo 'export PATH="$HOME/local/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc
#+end_src

** Building Texinfo

Texinfo is required for building Emacs. If your system's texinfo is missing or outdated, you can build it from source:

#+begin_src bash
# Navigate to source directory
cd ~/local/src

# Download texinfo source
wget https://ftp.gnu.org/gnu/texinfo/texinfo-6.8.tar.gz
tar xzf texinfo-6.8.tar.gz

# Create and use build directory
mkdir -p ~/local/build/texinfo
cd ~/local/build/texinfo

# Configure with appropriate paths
~/local/src/texinfo-6.8/configure --prefix=$HOME/local/opt/texinfo --bindir=$HOME/local/bin

# Build and install
make
make install

# Verify installation
which makeinfo
makeinfo --version
#+end_src

You can then use the locally installed texinfo when building Emacs by ensuring it's in your PATH:

#+begin_src bash
# When configuring Emacs, ensure the local bin directory is in your PATH
export PATH="$HOME/local/bin:$PATH"

# Or, if you prefer, explicitly set the MAKEINFO variable
~/local/src/emacs/configure \
  --prefix=$HOME/local/opt/emacs \
  --bindir=$HOME/local/bin \
  MAKEINFO=$HOME/local/bin/makeinfo \
  --with-native-compilation \
  --with-mailutils \
  --with-tiff=ifavailable \
  --with-gnutls=ifavailable
#+end_src

** Dependencies

#+begin_src bash
sudo apt-get install -y \
  gcc-10 libgccjit0 libgccjit-10-dev \
  libjansson4 libjansson-dev git \
  software-properties-common \
  automake texinfo
#+end_src

** Docker Build

#+begin_src bash
# Navigate to Emacs source directory
cd ~/local/src/emacs

# Create a Dockerfile
cat > Dockerfile << 'EOF'
FROM ubuntu:20.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common \
    gcc-10 libgccjit0 libgccjit-10-dev \
    libjansson4 libjansson-dev git \
    automake texinfo

# Add GCC repository for native compilation
RUN add-apt-repository ppa:ubuntu-toolchain-r/ppa \
    && apt-get update

# Get Emacs build dependencies
RUN apt-get build-dep -y emacs

# Set compiler for native compilation
ENV CC="gcc-10"

# Copy source code
COPY . /opt/emacs
WORKDIR /opt/emacs

# Build Emacs
RUN ./autogen.sh \
    && ./configure --with-native-compilation --with-mailutils \
    && make -j$(nproc) \
    && make install

ENTRYPOINT ["emacs"]
EOF

# Build the Docker image
docker build -t emacs-build .

# Run Emacs in Docker
docker run -it --rm emacs-build
#+end_src

** Important Configure Flags

- --prefix=$HOME/local/opt/emacs: Sets installation directory
- --bindir=$HOME/local/bin: Where executable binaries will be installed
- --with-native-compilation: Enable native compilation support (faster Elisp)
- --with-mailutils: Include mail utilities
- --with-tiff=ifavailable: Include TIFF support if available
- --with-gnutls=ifavailable: Include GnuTLS support if available
- --without-x: Build without X Window System support (optional, for terminal-only use)

** Purpose / General  Links

My adapation of https://github.com/chaoflow/.emacs.d

Original README:

Be prepared for rebases.

Better take a look at other sources for configuration files:

- [[-  https://github.com/redguardtoo/emacs.d/tree/master/lisp][https://github.com/redguardtoo/emacs.d/tree/master/lisp]]
- https://github.com/corecode/skel/tree/master/.emacs.d
- https://github.com/magnars/.emacs.d/
- https://github.com/cjohansen/.emacs.d
- https://github.com/technomancy/emacs-starter-kit from which I take inspiration or shamelessly copy.
- [[https://www.gnu.org/software/emacs/manual/html_node/emacs/index.html#Top][Emacs Manual]]
- [[https://www.emacswiki.org/emacs/ImenuMode#toc3][imenu and icycles]]
- [[http://avilpage.com/2015/05/automatically-pep8-your-python-code.html][Emacs Mode Hook for autopep]]
- http://www.coli.uni-saarland.de/~slemaguer/emacs/main.html#org67e2b1b
  -> moved https://github.com/seblemaguer/dotfiles
- https://github.com/daviwil/emacs-from-scratch - emacs from Scratch Series
- https://github.com/Schnouki
- https://github.com/tmtxt/.emacs.d/tree/master/config
- https://www.masteringemacs.org
- https://caiorss.github.io/Emacs-Elisp-Programming/Keybindings.html
- http://ergoemacs.org/emacs/emacs\_find\_replace.html
- https://github.com/enzuru/.emacs.d
- https://github.com/iqss/IQSS.emacs/ and https://iqss.github.io/IQSS.emacs/init.htm

* Languages / Modes


** C/C++
-  Cmake  IDE Package   https://github.com/atilaneves/cmake-ide
-  https://skebanga.github.io/cpp-dev-in-spacemacs/

** Org mode

-  http://www.coli.uni-saarland.de/~slemaguer/emacs/main.html#org3c16bce
-  http://doc.norang.ca/org-mode.html
-  https://sachachua.com/blog/2013/08/emacs-how-i-organize-my-org-files/
-  https://orgmode.org/worg/org-hacks.html
-  https://en.wikipedia.org/wiki/Getting\_Things\_Done

*** Capturing

-  C-c c - Capturn

**** Links für Capturing Templates
     :PROPERTIES:
     :CUSTOM_ID: links-für-capturing-templates
     :END:

-  https://gist.github.com/prassee/1d0678ad1c86481176a39ccb4441c53b
-  https://gist.github.com/spacebat/097f3e7469edf2eaa6a9
-  https://www.reddit.com/r/emacs/comments/7zqc7b/share\_your\_org\_capture\_templates/
-  Die Org-Config von ist sehr mächtig,
   https://github.com/sk8ingdom/.emacs.d/tree/master/. Diese habe ich
   assimiliert. Insbesondere die Capture-Templates sind ein sehr toller
   Ausgangspunkt. Der Hinweis ist auch aus dem Reddit-Post:
   https://www.reddit.com/r/emacs/comments/7zqc7b/share\_your\_org\_capture\_templates/

** Lisp
   :PROPERTIES:
   :CUSTOM_ID: lisp
   :END:

1. [[https://github.com/hypernumbers/learn_elisp_the_hard_way/tree/master/contents][Learn Emacs Lips the Hard Way]]
2. [[https://caiorss.github.io/Emacs-Elisp-Programming/Elisp_Programming.html#sec-4-2][Emacs Lisp caiorss]]
3. [[https://www.cs.utexas.edu/~novak/schemevscl.html][Elisp versus Scheme Lisp keywords]]
4. [[file:Learn%20Elisp%20the%20hard%20way][https://github.com/hypernumbers/learn\_elisp\_the\_hard\_way/tree/master/contents]]

** Python
   :PROPERTIES:
   :CUSTOM_ID: python
   :END:

- Elpy issues: https://github.com/jorgenschaefer/elpy/issues/842
[[https://avilpage.com/2015/05/automatically-pep8-your-python-code.html][- Anleitung für pep mode hook]]

*** LSP and Python

- [[https://vxlabs.com/2018/06/08/python-language-server-with-emacs-and-lsp-mode/][https://vxlabs.com/2018/06/08/python-language-server-with-emacs-and-lsp-mode/]]
- [[https://www.reddit.com/r/emacs/comments/4oyvcn/redbaron_for_emacs_refactor_your_python_method/][ed baron]]
- [[https://github.com/palantir/python-language-server][Palantir Python lsp server imple111mentation]]
- https://github.com/rememberYou/.emacs.d/blob/master/config.org#python
- add python from scratch link here
- https://www.youtube.com/watch?v=74zOY-vgkyw
- lsp languages https://emacs-lsp.github.io/lsp-mode/page/languages/
- https://github.com/seblemaguer/dotfiles -> has one too, no longer coli uni-saarland
- Medium Post on LSP: https://alpha2phi.medium.com/emacs-lsp-and-dap-7c1786282324



** Java IDE
   :PROPERTIES:
   :CUSTOM_ID: java-ide
   :END:

http://www.goldsborough.me/emacs,/java/2016/02/24/22-54-16-setting\_up\_emacs\_for\_java\_development/
http://www.skybert.net/emacs/java/
https://github.com/skybert/my-little-friends/blob/master/emacs/.emacs.d/tkj-java-meghanada.el
https://github.com/skybert/my-little-friends/blob/master/emacs/.emacs.d/tkj-java-meghanada.el




** Web Development
   :PROPERTIES:
   :CUSTOM_ID: web-development
   :END:

Currently used Major Modes - mmm mode are two multi-mode enginges web
mode. I have mainly configured - vue-mode for vue framework files -
js2-mode for javascript

*** Important Minor Modes
    :PROPERTIES:
    :CUSTOM_ID: important-minor-modes
    :END:

**** emmet mode
     :PROPERTIES:
     :CUSTOM_ID: emmet-mode
     :END:

Completion for css, js, html. Abbreviations on homepage,

https://github.com/smihica/emmet-mode

C-j

**** Company-web
     :PROPERTIES:
     :CUSTOM_ID: company-web
     :END:

Company backend for web completion https://github.com/osv/company-web
configured in setup-web-mode.el and setup-auto-complete.el

M-x company-web-html

see this for language server alternative
https://emacs.stackexchange.com/questions/55230/help-setting-up-company-mode-autocompletion-of-html-css-files

*** Web Mode -> Major Mode for mainly Templates, html
    :PROPERTIES:
    :CUSTOM_ID: web-mode---major-mode-for-mainly-templates-html
    :END:

Flycheck use eslint:
http://codewinds.com/blog/2015-04-02-emacs-flycheck-eslint-jsx.html

C-c C-f web-mode-fold-or-unfold C-c C-e i web-mode-element-insert C-c
C-s insert snippets M-; comment out regions C-c C-w show whitespaces C-c
C-m mark region

Selection Expansion C-n marks current element

Tag Navigation:

Closing element : type '</' and it happens in html similarly for
templates

Type faster: emmet-mode: But web-mode has sth similar d/ -> creates div,
/s creates spna

*** Vue Mode
   :PROPERTIES:
   :CUSTOM_ID: vue-mode
   :END:

-  To be described - Using lsp is quite cool

*** Web Development further links:
   :PROPERTIES:
   :CUSTOM_ID: web-development-further-links
   :END:

-  https://github.com/jerryhsieh/Emacs-config
-  https://blog.onionstudio.com.tw/emacs-%E5%AF%AB-vue-js/
-  https://emacs-lsp.github.io/lsp-ui/





** LSP und DAP
   :PROPERTIES:
   :CUSTOM_ID: lsp-und-dap
   :END:

- Emacs LSP Main Page https://emacs-lsp.github.io/lsp-mode/
- Emacs from scratch Video https://www.youtube.com/watch?v=E-NAM9U5JYE
- https://emacs-lsp.github.io/lsp-mode/page/languages/
- Dap https://emacs-lsp.github.io/dap-mode/page/configuration/
- Emacs-LSP Discussions at gitter https://gitter.im/emacs-lsp/lsp-mode?at=5df680feac14cc652c8c0e22


* Other Topics

** Helm
   :PROPERTIES:
   :CUSTOM_ID: helm
   :END:

1. [[https://tuhdo.github.io/helm-intro.html][A Package in a league of
   its own]]
2. [[https://github.com/emacs-helm/helm/wiki][helm-wiki]]
3. [[http://thescratchcastle.com/posts/emacs-and-helm.html][bloc post]]
4. [[file:allows%20to%20edit%20occurrences%20in%20many%20files%20too][helm-swoop]]

** Fill column indication
  :PROPERTIES:
  :CUSTOM_ID: fill-column-indication
  :END:

-  start using fci-mode
-  (setq fci-rule-column 100)
** Code Navigation usig Etags

** Etags Navigation

[[https://www.coverfire.com/archives/2004/06/24/emacs-source-code-navigation/][etags primer]]

-  =find . -name '*.[ch]' | xargs etags=
-  M-. (that's Meta-Period) and type the name of the function
-  M-* to navigate to last point
-  Use helm to navigate to tags: M-x helm-etags-select
-  Use projectile-regenerate-tags to generate tags before.


** .dir-locals
   :PROPERTIES:
   :CUSTOM_ID: dir-locals
   :END:

#+BEGIN_EXAMPLE elisp
(
 (nil . (
         (projectile-project-test-cmd . "pytest --color=yes app/  --ignore app/tests/  --cov=app/study --cov=app/report  --cov=app/core")
         ;; (compilation-read-command . nil)
         (py-pythonpath . "/home/audeering.local/cgeng/code/data_collection/aisoundlab/backend/app/")
         ;; (setq venv-dirlookup-names '(".projectile" ".venv" "pyenv" ".virtual"))
         ;; Automatically activating a virtualenv when using projectile
         ;; (setq projectile-switch-project-action 'venv-projectile-auto-workon)
         (eval . (progn
          (make-local-variable 'process-environment)
          (setq process-environment (copy-sequence process-environment))
          (setenv "PYTHONPATH" "/home/cgeng/code/app/:/home/cgeng/some_dir/")
          (setenv "WORKON_HOME" (expand-file-name "~/work/.envs"))
          ))
         )
  )
 (python-mode . (
                 ;; (pyvenv-activate . "~/.venvs/py37")
                 (lsp-pyright-venv-path . "~/.venvs/")
                 (subdirs . nil))
              )

)
#+END_EXAMPLE


*** Links

- https://emacs.stackexchange.com/questions/24907/how-to-use-dir-locals-el-with-projectile
- https://emacs.stackexchange.com/questions/13080/reloading-directory-local-variables
- https://emacs.stackexchange.com/questions/21955/calling-functions-in-dir-locals-in-emacs - cmake beispiele
- https://emacs.stackexchange.com/questions/61493/confused-regarding-dir-locals-el-and-projectile/61594#61594
- https://emacs.stackexchange.com/questions/63417/adding-directory-local-variable-for-projectile-test-command-is-not-working
- https://gist.github.com/sivakov512/99f288960475ca6c32c8c65483012c71 - uses .dir-locals to run python manage.py runserver

** Lern use-package and stream the configurations: https://github.com/jwiegley/use-package
